import 'dart:math';

/// Result object generated by [FarmerAiVerificationService].
class FarmerAiVerificationResult {
  final bool isAutoApproved;
  final double confidenceScore; // 0.0 to 1.0 (e.g. 0.95 = 95%)
  final String verificationMethod; // 'ai_auto_verified' or 'manual_admin'
  final List<String> passedChecks;
  final List<String> flaggedReasons;
  final String summaryNotes;
  final Map<String, dynamic> diagnostics;

  const FarmerAiVerificationResult({
    required this.isAutoApproved,
    required this.confidenceScore,
    required this.verificationMethod,
    required this.passedChecks,
    required this.flaggedReasons,
    required this.summaryNotes,
    this.diagnostics = const {},
  });

  Map<String, dynamic> toJson() => {
        'is_auto_approved': isAutoApproved,
        'confidence_score': confidenceScore,
        'verification_method': verificationMethod,
        'passed_checks': passedChecks,
        'flagged_reasons': flaggedReasons,
        'summary_notes': summaryNotes,
        'diagnostics': diagnostics,
      };
}

/// On-Device AI Verification Engine for Philippine Farmer Identity.
///
/// Combines Google ML Kit OCR text, PhilSys QR digital payload,
/// and live facial selfie landmarks to achieve tamper-proof auto-approval.
class FarmerAiVerificationService {
  /// Minimum confidence score (85%) required for instant auto-approval.
  static const double autoApprovalThreshold = 0.85;

  /// Evaluates farmer registration credentials using on-device computer vision & cross-matching algorithms.
  static FarmerAiVerificationResult evaluate({
    required String registeredFullName,
    required String registeredDob,
    String? frontOcrText,
    String? frontExtractedName,
    String? frontExtractedDob,
    String? frontExtractedPcn,
    String? backQrRawPayload,
    Map<String, dynamic>? backQrSubject,
    bool faceSelfieCaptured = false,
    String? idType = 'national_id',
    double? faceMatchSimilarity,
    bool? faceFoundOnId,
  }) {
    final passedChecks = <String>[];
    final flaggedReasons = <String>[];
    final diagnostics = <String, dynamic>{};

    double totalScore = 0.0; // max 100.0

    // ─────────────────────────────────────────────────────────────
    // 1. PhilSys QR Authenticity Check (Max 25 pts)
    // ─────────────────────────────────────────────────────────────
    bool qrValid = false;
    if (idType == 'national_id') {
      if (backQrSubject != null && backQrSubject.isNotEmpty) {
        qrValid = true;
        totalScore += 25.0;
        passedChecks.add('PhilSys Government QR payload verified');
        diagnostics['qr_status'] = 'valid_philsys_payload';
      } else if (backQrRawPayload != null && backQrRawPayload.trim().isNotEmpty) {
        // Raw string exists but wasn't decoded into JSON/JWT
        totalScore += 12.0;
        flaggedReasons.add('PhilSys QR format non-standard, manual review suggested');
        diagnostics['qr_status'] = 'raw_unparsed';
      } else {
        flaggedReasons.add('PhilSys Back QR code was not scanned or missing');
        diagnostics['qr_status'] = 'missing';
      }
    } else {
      // Alternative Government ID (Driver's License, Postal ID, PRC)
      totalScore += 20.0;
      passedChecks.add('Alternative Government ID submitted');
      diagnostics['qr_status'] = 'not_applicable';
    }

    // ─────────────────────────────────────────────────────────────
    // 2. Name Cross-Validation (Max 30 pts)
    // ─────────────────────────────────────────────────────────────
    final candidateNames = <String>[];
    if (frontExtractedName != null && frontExtractedName.trim().isNotEmpty) {
      candidateNames.add(frontExtractedName.trim());
    }

    if (backQrSubject != null) {
      final fName = backQrSubject['fName'] ?? backQrSubject['firstName'] ?? backQrSubject['First_Name'] ?? '';
      final mName = backQrSubject['mName'] ?? backQrSubject['middleName'] ?? backQrSubject['Middle_Name'] ?? '';
      final lName = backQrSubject['lName'] ?? backQrSubject['lastName'] ?? backQrSubject['Last_Name'] ?? '';
      final suffix = backQrSubject['Suffix'] ?? backQrSubject['suffix'] ?? '';
      final qrFullName = [fName, mName, lName, suffix]
          .where((e) => e.toString().trim().isNotEmpty)
          .join(' ');
      if (qrFullName.isNotEmpty) {
        candidateNames.add(qrFullName);
      }
    }

    double bestNameSimilarity = 0.0;
    String bestMatchedCandidate = '';

    for (final cand in candidateNames) {
      final sim = computeNameSimilarity(registeredFullName, cand);
      if (sim > bestNameSimilarity) {
        bestNameSimilarity = sim;
        bestMatchedCandidate = cand;
      }
    }

    // Also compare against raw OCR text if available
    if (frontOcrText != null && frontOcrText.isNotEmpty) {
      final ocrSim = computeNameInOcrTextSimilarity(registeredFullName, frontOcrText);
      if (ocrSim > bestNameSimilarity) {
        bestNameSimilarity = ocrSim;
        bestMatchedCandidate = 'OCR Text Match';
      }
    }

    diagnostics['name_similarity'] = bestNameSimilarity;
    diagnostics['matched_name'] = bestMatchedCandidate;

    if (bestNameSimilarity >= 0.85) {
      totalScore += 30.0;
      passedChecks.add('Legal Name matches ID ($bestMatchedCandidate - ${(bestNameSimilarity * 100).toStringAsFixed(0)}% match)');
    } else if (bestNameSimilarity >= 0.65) {
      final partialPts = 30.0 * (bestNameSimilarity / 0.85);
      totalScore += partialPts;
      flaggedReasons.add('Minor name difference ($registeredFullName vs $bestMatchedCandidate: ${(bestNameSimilarity * 100).toStringAsFixed(0)}% similarity)');
    } else {
      flaggedReasons.add('Name mismatch: Registered "$registeredFullName" differs significantly from ID data');
    }

    // ─────────────────────────────────────────────────────────────
    // 3. PCN (PhilSys Card Number) Cross-Check (Max 15 pts)
    // ─────────────────────────────────────────────────────────────
    if (idType == 'national_id') {
      final cleanFrontPcn = _sanitizePcn(frontExtractedPcn);
      String? cleanBackPcn;
      if (backQrSubject != null) {
        final pcnVal = backQrSubject['PCN'] ?? backQrSubject['pcn'] ?? backQrSubject['CardNumber'] ?? backQrSubject['idNumber'];
        if (pcnVal != null) {
          cleanBackPcn = _sanitizePcn(pcnVal.toString());
        }
      }

      if (cleanFrontPcn != null && cleanBackPcn != null && cleanFrontPcn.isNotEmpty && cleanBackPcn.isNotEmpty) {
        if (cleanFrontPcn == cleanBackPcn) {
          totalScore += 15.0;
          passedChecks.add('Front & Back PCN match ($cleanFrontPcn)');
          diagnostics['pcn_match'] = true;
        } else {
          flaggedReasons.add('PCN Mismatch: Front ($cleanFrontPcn) vs Back ($cleanBackPcn)');
          diagnostics['pcn_match'] = false;
        }
      } else if (cleanFrontPcn != null || cleanBackPcn != null) {
        totalScore += 10.0;
        passedChecks.add('PhilSys PCN format verified');
        diagnostics['pcn_match'] = 'single_side_verified';
      } else {
        flaggedReasons.add('PCN could not be detected from ID card');
        diagnostics['pcn_match'] = 'missing';
      }
    } else {
      totalScore += 15.0;
      passedChecks.add('Card identifier recorded');
    }

    // ─────────────────────────────────────────────────────────────
    // 4. Date of Birth Cross-Check (Max 10 pts)
    // ─────────────────────────────────────────────────────────────
    final normRegDob = _normalizeDob(registeredDob);
    String? normIdDob;
    if (backQrSubject != null) {
      final qDob = backQrSubject['DOB'] ?? backQrSubject['dob'] ?? backQrSubject['BirthDate'] ?? backQrSubject['birthDate'];
      if (qDob != null) normIdDob = _normalizeDob(qDob.toString());
    }
    if (normIdDob == null && frontExtractedDob != null) {
      normIdDob = _normalizeDob(frontExtractedDob);
    }

    if (normRegDob != null && normIdDob != null && normRegDob.isNotEmpty && normIdDob.isNotEmpty) {
      if (normRegDob == normIdDob) {
        totalScore += 10.0;
        passedChecks.add('Date of Birth matches ID ($normRegDob)');
        diagnostics['dob_match'] = true;
      } else {
        flaggedReasons.add('DOB discrepancy: Registered "$normRegDob" vs ID "$normIdDob"');
        diagnostics['dob_match'] = false;
      }
    } else if (normRegDob != null && normRegDob.isNotEmpty) {
      totalScore += 7.0;
      passedChecks.add('Registered Date of Birth format valid ($normRegDob)');
      diagnostics['dob_match'] = 'unverified_on_id';
    }

    // ─────────────────────────────────────────────────────────────
    // 5. Facial Liveness & Selfie Scan (Max 10 pts)
    // ─────────────────────────────────────────────────────────────
    if (faceSelfieCaptured) {
      totalScore += 10.0;
      passedChecks.add('Live centered facial selfie verified via ML Kit Face Detection');
      diagnostics['face_liveness'] = true;
    } else {
      flaggedReasons.add('Facial selfie was not scanned');
      diagnostics['face_liveness'] = false;
    }

    // ─────────────────────────────────────────────────────────────
    // 6. 1-to-1 Biometric Facial Comparison (Max 10 pts)
    // ─────────────────────────────────────────────────────────────
    bool faceMatchPassed = true;
    if (faceMatchSimilarity != null) {
      diagnostics['face_match_similarity'] = faceMatchSimilarity;
      if (faceMatchSimilarity >= 0.65) {
        totalScore += 10.0;
        passedChecks.add('1-to-1 Biometric Face Match Confirmed (${(faceMatchSimilarity * 100).toStringAsFixed(1)}%)');
        diagnostics['face_match_status'] = 'matched';
      } else {
        faceMatchPassed = false;
        flaggedReasons.add('Biometric Face Mismatch: Selfie does not match ID portrait (${(faceMatchSimilarity * 100).toStringAsFixed(1)}% match)');
        diagnostics['face_match_status'] = 'mismatch';
      }
    } else if (faceFoundOnId == false) {
      faceMatchPassed = false;
      flaggedReasons.add('No face detected on ID card portrait for biometric comparison');
      diagnostics['face_match_status'] = 'no_id_face';
    } else {
      // Default: passed if selfie was captured and no mismatch detected
      totalScore += 5.0;
      diagnostics['face_match_status'] = 'pending_or_skipped';
    }

    // Normalize confidence score between 0.0 and 1.0
    final confidenceScore = (totalScore / 100.0).clamp(0.0, 1.0);
    diagnostics['raw_score'] = totalScore;
    diagnostics['confidence_score'] = confidenceScore;

    // Strict Auto-Approval Gate:
    // Requires >= threshold AND face selfie AND biometric face match AND high name match AND valid QR
    final isAutoApproved = confidenceScore >= autoApprovalThreshold &&
        faceSelfieCaptured &&
        faceMatchPassed &&
        bestNameSimilarity >= 0.75 &&
        (idType != 'national_id' || qrValid);

    final summaryNotes = isAutoApproved
        ? 'AI Auto-Verified: Confidence ${(confidenceScore * 100).toStringAsFixed(1)}%. ${passedChecks.join(', ')}.'
        : 'Requires Admin Review: Confidence ${(confidenceScore * 100).toStringAsFixed(1)}%. Reasons: ${flaggedReasons.join('; ')}.';

    return FarmerAiVerificationResult(
      isAutoApproved: isAutoApproved,
      confidenceScore: confidenceScore,
      verificationMethod: isAutoApproved ? 'ai_auto_verified' : 'manual_admin',
      passedChecks: passedChecks,
      flaggedReasons: flaggedReasons,
      summaryNotes: summaryNotes,
      diagnostics: diagnostics,
    );
  }

  /// Calculates similarity between two names (0.0 to 1.0) using
  /// Token Sort + Levenshtein distance.
  static double computeNameSimilarity(String name1, String name2) {
    final n1 = _cleanString(name1);
    final n2 = _cleanString(name2);

    if (n1.isEmpty || n2.isEmpty) return 0.0;
    if (n1 == n2) return 1.0;

    // 1. Token sort comparison (e.g. "JUAN DELA CRUZ" vs "DELA CRUZ JUAN")
    final tokens1 = n1.split(' ')..sort();
    final tokens2 = n2.split(' ')..sort();

    final sorted1 = tokens1.join(' ');
    final sorted2 = tokens2.join(' ');
    if (sorted1 == sorted2) return 1.0;

    // 2. Token overlap (Jaccard similarity on tokens)
    final set1 = tokens1.toSet();
    final set2 = tokens2.toSet();
    final intersection = set1.intersection(set2).length;
    final union = set1.union(set2).length;
    final jaccard = union > 0 ? intersection / union : 0.0;

    // 3. Levenshtein ratio on sorted string
    final levRatio = _levenshteinRatio(sorted1, sorted2);

    // 4. Also check direct Levenshtein ratio
    final directLev = _levenshteinRatio(n1, n2);

    // Return the strongest metric
    return [jaccard, levRatio, directLev].reduce(max);
  }

  /// Checks if individual tokens of the registered name appear in the raw OCR text.
  static double computeNameInOcrTextSimilarity(String registeredName, String ocrText) {
    final cleanName = _cleanString(registeredName);
    final cleanOcr = _cleanString(ocrText);

    if (cleanName.isEmpty || cleanOcr.isEmpty) return 0.0;

    final tokens = cleanName.split(' ').where((t) => t.length >= 2).toList();
    if (tokens.isEmpty) return 0.0;

    int matchedTokens = 0;
    for (final token in tokens) {
      if (cleanOcr.contains(token)) {
        matchedTokens++;
      }
    }

    return matchedTokens / tokens.length;
  }

  static String _cleanString(String input) {
    return input
        .toUpperCase()
        .replaceAll(RegExp(r'[^A-Z0-9\s]'), '')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  static String? _sanitizePcn(String? pcn) {
    if (pcn == null) return null;
    final digitsOnly = pcn.replaceAll(RegExp(r'[^0-9]'), '');
    return digitsOnly.length >= 12 ? digitsOnly : null;
  }

  static String? _normalizeDob(String? dob) {
    if (dob == null || dob.trim().isEmpty) return null;
    final clean = dob.trim();

    // Already YYYY-MM-DD
    if (RegExp(r'^\d{4}-\d{2}-\d{2}$').hasMatch(clean)) {
      return clean;
    }

    // MM/DD/YYYY
    final slashMatch = RegExp(r'^(\d{1,2})/(\d{1,2})/(\d{4})$').firstMatch(clean);
    if (slashMatch != null) {
      final m = slashMatch.group(1)!.padLeft(2, '0');
      final d = slashMatch.group(2)!.padLeft(2, '0');
      final y = slashMatch.group(3)!;
      return '$y-$m-$d';
    }

    return clean;
  }

  static double _levenshteinRatio(String s, String t) {
    if (s == t) return 1.0;
    if (s.isEmpty || t.isEmpty) return 0.0;

    final d = List.generate(
      s.length + 1,
      (i) => List.filled(t.length + 1, 0),
    );

    for (int i = 0; i <= s.length; i++) {
      d[i][0] = i;
    }
    for (int j = 0; j <= t.length; j++) {
      d[0][j] = j;
    }

    for (int i = 1; i <= s.length; i++) {
      for (int j = 1; j <= t.length; j++) {
        final cost = s[i - 1] == t[j - 1] ? 0 : 1;
        d[i][j] = min(
          d[i - 1][j] + 1, // deletion
          min(
            d[i][j - 1] + 1, // insertion
            d[i - 1][j - 1] + cost, // substitution
          ),
        );
      }
    }

    final distance = d[s.length][t.length];
    final maxLength = max(s.length, t.length);
    return 1.0 - (distance / maxLength);
  }
}
