// File generated by the FlutterFire CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjlGgHnSlIJTOtb7munxmgLZXxy1bLmQ',
    appId: '1:971354937445:android:11d1cf7d729eda5b07ce8c',
    messagingSenderId: '971354937445',
    projectId: 'agridirect-8592b',
    storageBucket: 'agridirect-8592b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFjlGgHnSlIJTOtb7munxmgLZXxy1bLmQ',
    appId: '1:971354937445:ios:YOUR_APP_ID_HERE',
    messagingSenderId: '971354937445',
    projectId: 'agridirect-8592b',
    storageBucket: 'agridirect-8592b.firebasestorage.app',
    iosBundleId: 'com.example.agridirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFjlGgHnSlIJTOtb7munxmgLZXxy1bLmQ',
    appId: '1:971354937445:macos:YOUR_APP_ID_HERE',
    messagingSenderId: '971354937445',
    projectId: 'agridirect-8592b',
    storageBucket: 'agridirect-8592b.firebasestorage.app',
    iosBundleId: 'com.example.agridirect',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjlGgHnSlIJTOtb7munxmgLZXxy1bLmQ',
    appId: '1:971354937445:web:YOUR_APP_ID_HERE',
    messagingSenderId: '971354937445',
    projectId: 'agridirect-8592b',
    authDomain: 'agridirect-8592b.firebaseapp.com',
    storageBucket: 'agridirect-8592b.firebasestorage.app',
  );
}
