import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Firebase Configuration
/// Mobile (Android/iOS): reads config from google-services.json / GoogleService-Info.plist
///   — no firebase_options.dart needed.
/// Web: requires running `flutterfire configure` to generate firebase_options.dart,
///   then pass DefaultFirebaseOptions.currentPlatform to initializeApp.
class FirebaseConfig {
  static bool _initialized = false;

  static Future<void> initialize() async {
    if (_initialized) return;

    try {
      if (kIsWeb) {
        // Web requires explicit FirebaseOptions generated by `flutterfire configure`.
        // Until that file is generated, Firebase on web is skipped.
        // Run: dart pub global activate flutterfire_cli
        //      flutterfire configure --project=<your-firebase-project-id>
        debugPrint('Firebase web init skipped — run flutterfire configure to enable');
        return;
      }

      // Mobile: Firebase reads from google-services.json (Android) or
      // GoogleService-Info.plist (iOS) automatically — no options needed.
      await Firebase.initializeApp();
      _initialized = true;
      debugPrint('Firebase initialized (mobile)');
    } catch (e) {
      debugPrint('Firebase initialization error: $e');
      // Non-fatal — app continues without Firebase if init fails
    }
  }
}
